### ISSUE TITLE
How to get the trained weights  ?

### ISSUE THREAD

**Issue by Samjith888** [Xiangtaokong/ClassSR#15]
Thank for the great work.

I have trained on a custom dataset by using ClassSR repo. But not able to find the trained weights after each epochs . Should i wait to complete the entire epochs to get the trained  weights ?

**Comment by Xiangtaokong** [comment]
Thank for your attention.
Change the 'save_checkpoint_freq: !!float 2000' in train.yml. It controls the freq of saving trained weights.

**Comment by Samjith888** [comment]
Thanks , i got the trained weights for SRResNet . Now i want to run the model on a LR image to make it HR. In the repo , you have mentioned the following command to test the model.
`python test_ClassSR.py -opt options/test/test_ClassSR_SRResNet.yml`

test_ClassSR_SRResNet.yml`

> datasets:
>   test_1:
>     name: test2k
>     mode: LQGT
>     dataroot_GT: /data0/xtkong/data/test2k/HR/X4
>     dataroot_LQ: /data0/xtkong/data/test2k/LR/X4
>   test_2:
>     name: test4k
>     mode: LQGT
>     dataroot_GT: /data0/xtkong/data/test4k/HR/X4
>     dataroot_LQ: /data0/xtkong/data/test4k/LR/X4
>   test_3:
>     name: test8k
>     mode: LQGT
>     dataroot_GT: /data0/xtkong/data/test8k/HR/X4
>     dataroot_LQ: /data0/xtkong/data/test8k/LR/X4

Above fields are in the file. But i just want to make convert a LR image into HR image by using the trained weight. How can i do this ?

**Comment by Xiangtaokong** [comment]
Follow the guidance of “how to test a single bransh”.
Use the test.py and test_srresnet.yaml, replace the path of model and data in the file.
If you are new to SR tasks, you can follow the basicSR repo～It must be helpful for you.



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 15, 2021 19:32 PM
To: ***@***.***&gt;;
Cc: "Xiangtao ***@***.******@***.***&gt;;
Subject: Re: [Xiangtaokong/ClassSR] How to get the trained weights  ? (#15)




 
Thanks , i got the trained weights for SRResNet . Now i want to run the model on a LR image to make it HR. In the repo , you have mentioned the following command to test the model.
 python test_ClassSR.py -opt options/test/test_ClassSR_SRResNet.yml
 
test_ClassSR_SRResNet.yml`
  
datasets:
 test_1:
 name: test2k
 mode: LQGT
 dataroot_GT: /data0/xtkong/data/test2k/HR/X4
 dataroot_LQ: /data0/xtkong/data/test2k/LR/X4
 test_2:
 name: test4k
 mode: LQGT
 dataroot_GT: /data0/xtkong/data/test4k/HR/X4
 dataroot_LQ: /data0/xtkong/data/test4k/LR/X4
 test_3:
 name: test8k
 mode: LQGT
 dataroot_GT: /data0/xtkong/data/test8k/HR/X4
 dataroot_LQ: /data0/xtkong/data/test8k/LR/X4
  
Above fields are in the file. But i just want to make convert a LR image into HR image by using the trained weight. How can i do this ?

**Comment by Samjith888** [comment]
Just gone through basicSR repo. For testing the model, we need to mention only the LR images path on their configuration file.

 
```yaml
# datasets
datasets:
  test_1:  # the 1st test dataset
    name: Set5
    type: SingleImageDataset
    dataroot_lq: datasets/Set5/LRbicx4
    io_backend:
      type: disk
# path
path:
  pretrain_network_g: experiments/pretrained_models/ESRGAN/ESRGAN_SRx4_DF2KOST_official-ff704c30.pth
  strict_load_g: true
# validation settings
val:
  save_img: true
  suffix: ~  # add suffix to saved images, if None, use exp name
```


Idea behind this project is to convert LR images into HR images .  But In ClassSR repo, why we should add both LR and its HR images. When i removed the HR path , I'm getting the following error too.


```
Testing [class1]...
Traceback (most recent call last):
  File "test_ClassSR.py", line 70, in <module>
    num_res = visuals['num_res']
KeyError: 'num_res'
```


test_SRResNet.yml

```
name: test_SRResNet_branch1
model: sr
distortion: sr
scale: 4
crop_border: ~  # crop border when evaluation. If None(~), crop the scale pixels
gpu_ids: [0]
#### network structures
network_G:
  which_model_G: MSRResNet
  in_nc: 3
  out_nc: 3
  nf: 36
  nb: 16
  upscale: 4
datasets:
  test1:
    name: class1
    mode: LQGT
    dataroot_GT: /home/usr/ClassSR/test_images/LR
    # dataroot_LQ: /data0/xtkong/data/DIV2K_valid_HR_sub_psnr_LR_class1
  # test2:
  #   name: class2
  #   mode: LQGT
  #   dataroot_GT: /data0/xtkong/data/DIV2K_valid_HR_sub_psnr_GT_class2
  #   dataroot_LQ: /data0/xtkong/data/DIV2K_valid_HR_sub_psnr_LR_class2
  # test3:
  #   name: class3
  #   mode: LQGT
  #   dataroot_GT: /data0/xtkong/data/DIV2K_valid_HR_sub_psnr_GT_class3
  #   dataroot_LQ: /data0/xtkong/data/DIV2K_valid_HR_sub_psnr_LR_class3

#### path
path:
  pretrain_model_G: /home/usr/ClassSR/experiments/SRResNet2000_G.pt
```

**Comment by Xiangtaokong** [comment]
First, using ‘python test.py -opt options/test/test_SRResNet.yml’ to test a single branch (e.g. SRResNet), instead of ‘python test_ClassSR.py -opt options/test/test_ClassSR_SRResNet.yml’.

If you want to test ClassSR, you first need to train a ClassSR model using 'python train_ClassSR.py -opt options/train/train_ClassSR_SRResNet.yml' (or download our model, not a single branch e.g. SRResNet).

This project using GT to measure the quality of reconstruction (PSNR). If you don't have GT, you can comment out the code of calculating PSNR (Or just find a big image that fit the size(x4), then you can run the model with out changing the code).

**Comment by Samjith888** [comment]
I have tried using your pretrained model "ClassSR_SRResNet.pth" and tried by testing the model using "test_ClassSR.py" with 4k images, (your suggestions from the last reply : "Or just find a big image that fit the size(x4), then you can run the model with out changing the code")

But  i got the following error.  

```
Testing [class1]...
Traceback (most recent call last):
  File "test_ClassSR.py", line 70, in <module>
    num_res = visuals['num_res']
KeyError: 'num_res'

```

Then i have commented out the PSNR code block, 
test_ClassSR.py

```
import os.path as osp
import logging
import time
import argparse
from collections import OrderedDict
import options.options as option
import utils.util as util
from data.util import bgr2ycbcr
from data import create_dataset, create_dataloader
from models import create_model
import numpy as np
#### options
parser = argparse.ArgumentParser()
parser.add_argument("-opt", type=str, required=True, help="Path to options YMAL file.")
opt = option.parse(parser.parse_args().opt, is_train=False)
opt = option.dict_to_nonedict(opt)
util.mkdirs(
    (
        path
        for key, path in opt["path"].items()
        if not key == "experiments_root" and "pretrain_model" not in key and "resume" not in key
    )
)
util.setup_logger("base", opt["path"]["log"], "test_" + opt["name"], level=logging.INFO, screen=True, tofile=True)
logger = logging.getLogger("base")
logger.info(option.dict2str(opt))
opt_net = opt["network_G"]
which_model = opt_net["which_model_G"]
#### Create test dataset and dataloader
test_loaders = []
for phase, dataset_opt in sorted(opt["datasets"].items()):
    test_set = create_dataset(dataset_opt)
    test_loader = create_dataloader(test_set, dataset_opt)
    logger.info("Number of test images in [{:s}]: {:d}".format(dataset_opt["name"], len(test_set)))
    test_loaders.append(test_loader)
model = create_model(opt)
for test_loader in test_loaders:
    test_set_name = test_loader.dataset.opt["name"]
    logger.info("\nTesting [{:s}]...".format(test_set_name))
    test_start_time = time.time()
    dataset_dir = osp.join(opt["path"]["results_root"], test_set_name)
    util.mkdir(dataset_dir)
    test_results = OrderedDict()
    test_results["psnr"] = []
    test_results["ssim"] = []
    test_results["psnr_y"] = []
    test_results["ssim_y"] = []
    avg_psnr = 0.0
    idx = 0
    num_ress = [0, 0, 0]
    for data in test_loader:
        need_GT = True
        model.feed_data(data, need_GT=need_GT)
        img_path = data["GT_path"][0] if need_GT else data["LQ_path"][0]
        img_name = osp.splitext(osp.basename(img_path))[0]
        model.test()
        visuals = model.get_current_visuals(need_GT=need_GT)
        sr_img = visuals["rlt"]  # uint8
        if opt["add_mask"]:
            sr_img_mask = visuals["rlt_mask"]
        # num_res = visuals['num_res']
        # psnr_res = visuals["psnr_res"]
        print(sr_img)
        # save images
        suffix = opt["suffix"]
        if suffix:
            save_img_path = osp.join(dataset_dir, img_name + suffix + ".png")
        else:
            save_img_path = osp.join(dataset_dir, img_name + ".png")
        util.save_img(sr_img, save_img_path)
        if opt["add_mask"]:
            util.save_img(sr_img_mask, save_img_path.split(".pn")[0] + "_mask.png")

```

test_ClassSR_SRResNet.yml
```
name: ClassSR_SRResNet
suffix: ~  # add suffix to saved images
model: ClassSR
distortion: sr
scale: 4
patch_size: 32
step: 28
crop_border: ~  # crop border when evaluation. If None(~), crop the scale pixels
gpu_ids: [0]
add_mask: False
datasets:
  # test_1:
  #   name: test2k
  #   mode: LQGT
  #   dataroot_GT: /home/usr/ClassSR/test_images/HR
  test_2:
    name: test4k
    mode: LQGT
    dataroot_GT: /home/usr/ClassSR/test_images/HR
  # test_3:
  #   name: test8k
  #   mode: LQGT
  #   dataroot_GT: /data0/xtkong/data/test8k/HR/X4
  #   dataroot_LQ: /data0/xtkong/data/test8k/LR/X4

#### network structures
network_G:
  which_model_G: classSR_3class_srresnet
  in_nc: 3
  out_nc: 3
#### path
path:
  pretrain_model_G: /home/usr/ClassSR/experiments/ClassSR_SRResNet.pth
  pretrain_model_classifier: ~
  pretrain_model_G_branch1: ~
  pretrain_model_G_branch2: ~
  pretrain_model_G_branch3: ~
```


Getting the following error
```

Testing [test4k]...
Traceback (most recent call last):
  File "test_ClassSR.py", line 65, in <module>
    model.test()
  File "/home/samjith/Projects/ClassSR/codes/models/ClassSR_model.py", line 195, in test
    self.fake_H = self.combine(sr_list, num_h, num_w, h, w, self.patch_size, self.step)
  File "/home/samjith/Projects/ClassSR/codes/models/ClassSR_model.py", line 286, in combine
    sr_img[i*step*self.scale:i*step*self.scale+patch_size*self.scale,j*step*self.scale:j*step*self.scale+patch_size*self.scale,:]+=sr_list[index]
IndexError: list index out of range

```
